name: Trigger Fork Sync
on:
  push:
    branches:
      - main
  workflow_dispatch: # This allows you to test it with a button

jobs:
  ping_fork:
    runs-on: ubuntu-latest
    steps:
      - name: Send signal to fork
        uses: peter-evans/repository-dispatch@v3
        with:
          # This MUST match the secret name in your Settings
          token: ${{ secrets.MY_PAT }} 
          repository: OfficialPillipot/pillipot-webapp
          event-type: upstream_updated
